#!/usr/bin/env sh

docker buildx bake dev

if ! docker volume inspect xx-pkg-cache >/dev/null 2>&1; then
  docker volume create xx-pkg-cache >/dev/null 2>&1
fi

docker run -it --rm -v xx-pkg-cache:/pkg-cache ghcr.io/loong64/tonistiigi/xx:dev
docker rmi ghcr.io/loong64/tonistiigi/xx:dev
