name: bats-assert

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/bats-assert.yml'
      - 'util/bats-assert/**'
      - 'docker-bake.hcl'
  pull_request:
    paths:
      - '.github/workflows/bats-assert.yml'
      - 'util/bats-assert/**'
      - 'docker-bake.hcl'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Test
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}:util/bats-assert"
          targets: test
      -
        name: Publish
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}:util/bats-assert"
          targets: all
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
