name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate
        uses: docker/bake-action@v6
        with:
          targets: validate

  test:
    uses: ./.github/workflows/.test.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            image: alpine:3.21
            base: alpine
            allow-failure: false
          -
            image: debian:trixie
            base: debian
            allow-failure: true
    with:
      image: ${{ matrix.image }}
      base: ${{ matrix.base }}
      allow-failure: ${{ matrix.allow-failure }}

  build:
    runs-on: ubuntu-latest
    needs:
      - validate
      - test
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/loong64/xx
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          bake-target: meta-helper
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: xx-all
          push: true
