name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate
        uses: docker/bake-action@v6
        with:
          targets: validate

  test:
    uses: ./.github/workflows/.test.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            image: alpine:3.18
            base: alpine
            allow-failure: true
          -
            image: alpine:3.19
            base: alpine
            allow-failure: true
          -
            image: alpine:3.20
            base: alpine
            allow-failure: true
          -
            image: alpine:3.21
            base: alpine
            allow-failure: false
          -
            image: alpine:3.22
            base: alpine
            allow-failure: false
          -
            image: alpine:edge
            base: alpine
            allow-failure: true
          -
            image: debian:bookworm
            base: debian
            allow-failure: true
          -
            image: debian:bookworm-backports
            base: debian
            allow-failure: true
          -
            image: debian:trixie
            base: debian
            allow-failure: true
          -
            image: debian:sid
            base: debian
            allow-failure: true
          -
            image: ubuntu:20.04
            base: debian
            allow-failure: true
          -
            image: ubuntu:22.04
            base: debian
            allow-failure: true
          -
            image: ubuntu:24.04
            base: debian
            allow-failure: true
          -
            image: redhat/ubi8
            base: rhel
            allow-failure: false
          -
            image: fedora:39
            base: rhel
            allow-failure: false
          -
            image: fedora:40
            base: rhel
            allow-failure: false
          -
            image: fedora:41
            base: rhel
            allow-failure: false
          -
            image: fedora:42
            base: rhel
            allow-failure: false
          -
            image: centos:7
            base: rhel
            allow-failure: false
          -
            image: rockylinux/rockylinux:8
            base: rhel
            allow-failure: false
          -
            image: rockylinux/rockylinux:9
            base: rhel
            allow-failure: false
          -
            image: rockylinux/rockylinux:10
            base: rhel
            allow-failure: false
          -
            image: oraclelinux:8
            base: rhel
            allow-failure: false
          -
            image: oraclelinux:9
            base: rhel
            allow-failure: false
    with:
      image: ${{ matrix.image }}
      base: ${{ matrix.base }}
      allow-failure: ${{ matrix.allow-failure }}

  build:
    runs-on: ubuntu-latest
    needs:
      - validate
      - test
    steps:
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/loong64/tonistiigi/xx
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          bake-target: meta-helper
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: xx-all
          push: ${{ github.event_name != 'pull_request' }}
