name: llvm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/llvm.yml'
      - 'src/llvm/**'
      - 'docker-bake.hcl'
  pull_request:
    paths:
      - '.github/workflows/llvm.yml'
      - 'src/llvm/**'
      - 'docker-bake.hcl'

jobs:
  compiler-rt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          targets: compiler-rt

  libcxx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          targets: compiler-rt
